### ISSUE TITLE
How to override same css class in css-to-mui-loader like standard css 

### ISSUE THREAD

**Issue by Kaliyani** [mcdougal/css-to-mui-loader#1]
Hi Team,

I am very new to Material Design. Currently i am exploring Material UI with ReactJS. Basically i am trying to replicate the same behavior as Standard CSS behavior. Please find my issue below,

I have created css file as (styles.css) below,

.button {
    background: $(theme.palette.secondary.main);
    padding: 2su; /* Material UI spacing units */
}
   
.button:hover {
    background: $(theme.palette.primary.light);
}

.button {
    background: #f08373;
    padding: 3su; /* Material UI spacing units */
    text-transform: lowercase;
}

My react code as below,

import React from 'react'
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';
import style from './style.css';
import classNames from 'classnames'
 
const MyComponent = (props) =>{
    const { classes} = props
    console.log(classes)
    return(
        <Button className={classNames(classes.button, classes.label)}>
            Click Me
        </Button>
    )
}

export default withStyles(style)(MyComponent)

When i try to run my code, i am getting Error like,

Failed to compile.

**./src/MyComponent.js
Attempted import error: './style.css' does not contain a default export (imported as 'style').**

Here i am trying to override the css class name .button. Compiler throws an error. 

When i modified the same css as below, 

.button {
    background: $(theme.palette.secondary.main);
    padding: 2su; /* Material UI spacing units */
}
   
.button:hover {
    background: $(theme.palette.primary.light);
}

.button {
    text-transform: lowercase;
}

Successfully merged two .button class as one. 

Can you please help to me to override the css class name.

**Comment by mcdougal** [comment]
Thanks for the bug report! This definitely looks like a real issue. I will not have a chance to look into it for a few days but I'll try to fix it as soon as possible.

In the meantime, do you need to have the `.button` class defined twice? In the example with the bug, the `background` and `padding` in the first `.button` class never gets applied:

```
.button {
  background: $(theme.palette.secondary.main); /* Never applies */
  padding: 2su; /* Never applies */
}

.button:hover {
  background: $(theme.palette.primary.light);
}

.button {
  background: #f08373;
  padding: 3su;
  text-transform: lowercase;
}
```

and it would be functionally equivalent and will likely compile properly if written like this:

```
.button {
  background: #f08373;
  padding: 3su;
  text-transform: lowercase;
}

.button:hover {
  background: $(theme.palette.primary.light);
}
```

Let me know if there are details of your use case that would prevent you from using workaround.

**Comment by mcdougal** [comment]
I actually just tried to reproduce this and I did not receive the same error.

Which version of Material UI are you using and can you paste your webpack config?

Here is my reproduction attempt. Perhaps you can point out if I am doing anything differently:

Test.js
```
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';
import classNames from 'classnames';
import React from 'react';

import style from './style.css';

const MyComponent = (props) => {
  const { classes } = props;
  console.log(classes);
  return (
    <Button className={classNames(classes.button, classes.label)}>
      Click Me
    </Button>
  );
};

export default withStyles(style)(MyComponent);
```

style.css
```
.button {
  background: $(theme.palette.secondary.main);
  padding: 2su; /* Material UI spacing units */
}

.button:hover {
  background: $(theme.palette.primary.light);
}

.button {
  background: #f08373;
  padding: 3su; /* Material UI spacing units */
  text-transform: lowercase;
}
```

Resulting `<style>` block in the HTML:
![image](https://user-images.githubusercontent.com/1130572/49304558-b2ff0b00-f49a-11e8-8aca-3c60b9d0d03e.png)

Resulting button:
![image](https://user-images.githubusercontent.com/1130572/49304572-c27e5400-f49a-11e8-8ecd-fcc8eea47f15.png)

**Comment by Kaliyani** [comment]
> Thanks for the bug report! This definitely looks like a real issue. I will not have a chance to look into it for a few days but I'll try to fix it as soon as possible.
> 
> In the meantime, do you need to have the `.button` class defined twice? In the example with the bug, the `background` and `padding` in the first `.button` class never gets applied:
> 
> ```css
> .button {
>   background: $(theme.palette.secondary.main); /* Never applies */
>   padding: 2su; /* Never applies */
> }
> 
> .button:hover {
>   background: $(theme.palette.primary.light);
> }
> 
> .button {
>   background: #f08373;
>   padding: 3su;
>   text-transform: lowercase;
> }
> ```
> 
> and it would be functionally equivalent and will likely compile properly if written like this:
> 
> ```css
> .button {
>   background: #f08373;
>   padding: 3su;
>   text-transform: lowercase;
> }
> 
> .button:hover {
>   background: $(theme.palette.primary.light);
> }
> ```
> 
> Let me know if there are details of your use case that would prevent you from using workaround.

Thank you so much for reply. 

Here i am trying to replicate what the standard css will do. In standard css if you decalred .button class twice in same file, it will merge and override with last declared one like below,
First one
---------
```
.button {
 background: #f08373;
  padding: 3px;
  text-transform: lowercase;
}
```

Second one
--------------
```
.button {
 background: #ffffff;
  padding: 10px;
}
```

My Result will be,
--------------------
```
.button {
 background: #ffffff;
  padding: 10px;
  text-transform: lowercase;
}
```
this is what i am trying to do in above sample code. Correct me if i am wrong.

**Comment by Kaliyani** [comment]
> I actually just tried to reproduce this and I did not receive the same error.
> 
> Which version of Material UI are you using and can you paste your webpack config?
> 
> Here is my reproduction attempt. Perhaps you can point out if I am doing anything differently:
> 
> Test.js
> 
> ```js
> import Button from '@material-ui/core/Button';
> import { withStyles } from '@material-ui/core/styles';
> import classNames from 'classnames';
> import React from 'react';
> 
> import style from './style.css';
> 
> const MyComponent = (props) => {
>   const { classes } = props;
>   console.log(classes);
>   return (
>     <Button className={classNames(classes.button, classes.label)}>
>       Click Me
>     </Button>
>   );
> };
> 
> export default withStyles(style)(MyComponent);
> ```
> 
> style.css
> 
> ```css
> .button {
>   background: $(theme.palette.secondary.main);
>   padding: 2su; /* Material UI spacing units */
> }
> 
> .button:hover {
>   background: $(theme.palette.primary.light);
> }
> 
> .button {
>   background: #f08373;
>   padding: 3su; /* Material UI spacing units */
>   text-transform: lowercase;
> }
> ```
> 
> Resulting `<style>` block in the HTML:
> ![image](https://user-images.githubusercontent.com/1130572/49304558-b2ff0b00-f49a-11e8-8aca-3c60b9d0d03e.png)
> 
> Resulting button:
> ![image](https://user-images.githubusercontent.com/1130572/49304572-c27e5400-f49a-11e8-8ecd-fcc8eea47f15.png)

Here i have attached my webpack.cong.dev.js and package.json file for your reference.

[packagejson.txt](https://github.com/mcdougal/css-to-mui-loader/files/2636467/packagejson.txt)
[webpack.config.dev.txt](https://github.com/mcdougal/css-to-mui-loader/files/2636468/webpack.config.dev.txt)

I am using below material version,

"@material-ui/core": "^3.6.0",
"@material-ui/icons": "^3.0.1",

Please go through my config file and correct me if i did any wrong configuration. 

Thanks in Adavance.....
